### ISSUE TITLE
errors my core

### ISSUE THREAD

**Issue by hoodz123** [project-codex/cx-payslip#4]
so im trying to replace the functions for pay check lua just errors my core and idea or where actually to change???

**Comment by hoodz123** [comment]
the only event i see and when i change from this Player.Functions.AddMoney('bank', payment) to Your Suggestion It Errors

**Comment by darkets** [comment]
Because you need to define the player's citizen by Player.PlayerData.citizenid

**Comment by hoodz123** [comment]
how do i do this you said replace on function ?

**Comment by hoodz123** [comment]
could you possibly right it for me id be highly appreciated

**Comment by darkets** [comment]
Please stop spamming issues and join our Discord for support: https://discord.gg/3M3TUjJ2
